### ISSUE TITLE
ButtonDownFcn  not working?

### ISSUE THREAD

**Issue by ironsuperdev** [pbaezr/olduitable#3]
```
hf = figure;
ht = olduitable(hf, ...
                'Fontsize', 25, ...     
                'ColumnEditable', [true true true], ...                            
                'data', {100 100 0},...
                'unit', 'normalized',...
                'position', [0 0 1 1]); 
ht.ButtonDownFcn = 'disp(''a mouse button was pressed1'')';
ht.CellSelectionCallback = 'disp(''a mouse button was pressed2'')';
```

Hi, why is in this case ButtonDownFcn  is not invoked? Tested on 2018b

```
Untitled2
a mouse button was pressed2
a mouse button was pressed2
a mouse button was pressed2
a mouse button was pressed2
a mouse button was pressed2
a mouse button was pressed2
```

**Comment by pbaezr** [comment]
Hi, this was decided trying to replicate to Matlab uitable (where the ButtonDownFcn is triggered in its full form when the 'Enable' property is off or inactive, otherwise it is only called when right-clicked).

Now for an olduitable object, if 'Enable' property in an 'on' state, the ButtonDownFcn is triggered when the click is made in any place except the table data (corner, headers and white space).

Either way, I will enable the option for the ButtonDownFcn to be activated for any 'Enable' property value.
